name: oxen_wallet
description: A Wallet for Oxen.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3


# keytool -genkey -v -keystore c:\Users\konst\key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl: ^0.17.0
  url_launcher: ^6.0.3
  qr: ^2.0.0
  uuid: ^3.0.3
  shared_preferences: ^0.5.12+4
  flutter_secure_storage: ^4.1.0
  provider: ^5.0.0
  rxdart: ^0.26.0
  yaml: ^3.1.0
  barcode_scan: any # outdated and should be replaced
  http: ^0.13.1
  path_provider: ^1.6.28
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+2
  flutter_slidable: ^0.5.7
  # share: ^0.6.2+1
  esys_flutter_share: ^1.0.2
  date_range_picker: ^1.0.7
  dio: ^4.0.0
  oxen_coin:
    path: ./oxen_coin
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  local_auth: ^1.1.0
  package_info: ^2.0.0
  devicelocale: ^0.4.1
  auto_size_text: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.0
  basic_utils: ^3.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  build_resolvers: ^1.5.1
  mobx_codegen: ^1.1.0+1
  hive_generator: ^0.8.1
  flutter_launcher_icons: ^0.9.0
  pedantic: ^1.8.0


#flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/app_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#DBF7F5"
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/node_list.yml
    - assets/testnet_node_list.yml
    - assets/changelog.yml
    - assets/text/
    - assets/faq/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Semibold.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
